#!/usr/bin/env fish

set script_dir (realpath (dirname (status --current-filename)))

set plugin_name $argv[1]
if [ "$plugin_name" = "" ]
    echo "Please input plugin_name as the 1st argument."
    exit 1
end

sd "PLUGIN_NAME" "$plugin_name" (fd -e .fish -e .md)
rename -s "PLUGIN_NAME" "$plugin_name" (fd -e .fish -e .md)
